# Generated by Django 4.2.18 on 2025-03-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={},
        ),
        migrations.AddField(
            model_name='blogger',
            name='github_profile',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Your Instagram handle without @', max_length=50),
        ),
        migrations.AddField(
            model_name='blogger',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='blogger',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Your Twitter handle without @', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='blog.tag'),
        ),
    ]
